sudo: false
language: ruby
rvm:
  - 2.2.1
bundler_args: --without production
addons:
  postgresql: "9.3"
before_script:
  - psql -c 'create database cuiner_test;' -U postgres
  - printf 'test:\n  adapter: postgresql\n  database: cuiner_test\n  username: postgres' > config/database.yml
