# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe70e8affa0d572dd1b94ade821a9363fea4ec684b80565e4ba316e0488257ca2619faeb486b83f573f55bd470090069735444e2fd77475efebf8e9625ae72e0

test:
  secret_key_base: b0ade198895b47f4c48157cfe1830656c547d9ff31d49c85972c22c252fa05b16cc9668c1f1e73b25a51d90b3204e5294f3498f927fd61fe8b0a4aca2138cb8a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
